name = "ftoolbox-frontend"
pages_build_output_dir = ".svelte-kit/cloudflare"
compatibility_date = "2025-01-06"

# Build configuration is handled by the deployment scripts in package.json
# The adapter-cloudflare will output to .svelte-kit/cloudflare

# IMPORTANT: Environment variables for SvelteKit must be set in:
# 1. Cloudflare Pages dashboard for production builds
# 2. Via command line when building locally (see package.json scripts)
# 
# The [vars] section below does NOT work for build-time environment variables
# in SvelteKit as they need to be available during the build process.