name = "ftoolbox-frontend"
main = ".svelte-kit/cloudflare/_worker.js"
compatibility_date = "2025-06-30"

[assets]
directory = ".svelte-kit/cloudflare"
binding = "ASSETS"

[build]
command = "PUBLIC_API_URL=https://ftoolbox-api.zergo0.dev pnpm build"

[vars]
PUBLIC_API_URL = "https://ftoolbox-api.zergo0.dev"

[[routes]]
pattern = "ftoolbox.zergo0.dev"
custom_domain = true