root = "."
testdata_dir = "testdata"
tmp_dir = "backend/tmp"

[build]
  cmd = "go build -o backend/main backend/cmd/api/main.go"
  exclude_dir = ["assets", "tmp", "vendor", "testdata", "backend/tmp"]
  exclude_regex = ["_test.go"]
  exclude_unchanged = false
  full_bin = "cd ./backend && ./main"
  include_dir = ["backend", "shared"]
  include_ext = ["go", "tpl", "tmpl", "html"]
  send_interrupt = true

[color]
  app = ""
  build = "yellow"
  main = "magenta"
  runner = "green"
  watcher = "cyan"

[log]
  main_only = false
  time = true

[misc]
  clean_on_exit = true

[screen]
  clear_on_rebuild = false
  keep_scroll = true