services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    volumes:
      - ./sqlite.db:/app/sqlite.db
    env_file:
      - .env
    restart: unless-stopped
