services:
  mariadb:
    image: mariadb:lts
    container_name: ftoolbox-mariadb
    restart: unless-stopped
    env_file:
      - ./ftoolbox-backend.env
    volumes:
      - ./mariadb_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      start_period: 10s
      interval: 10s
      timeout: 5s
      retries: 3

  migrate:
    image: ftoolbox-migrate:latest
    container_name: ftoolbox-migrate
    depends_on:
      mariadb:
        condition: service_healthy
    env_file:
      - ./ftoolbox-backend.env
    volumes:
      - ./sqlite.db:/data/sqlite.db:ro
    command: ["/data/sqlite.db"]

volumes:
  mariadb_data:
    name: ftoolbox-mariadb-data
